import { SourceRecord } from '../db/pool.js';

// Export sources as BibTeX (.bib)
export function exportToBibTeX(sources: SourceRecord[]): string {
  const entries: string[] = [];

  for (const s of sources) {
    const firstAuthor = s.authors && s.authors[0] ? s.authors[0].split(' ').pop() || 'Scholar' : 'Unknown';
    const year = s.year || new Date().getFullYear();
    const cleanId = `${firstAuthor.toLowerCase()}${year}${s.title.slice(0, 10).replace(/[^a-zA-Z0-9]/g, '')}`;

    const authorString = s.authors && s.authors.length > 0 ? s.authors.join(' and ') : 'Unknown';

    entries.push(`@article{${cleanId},
  title = {${s.title}},
  author = {${authorString}},
  year = {${year}},
  journal = {${s.venue || 'Academic Repository'}},
  url = {${s.url || ''}},
  doi = {${s.doi || ''}}
}`);
  }

  return entries.join('\n\n');
}

// Export sources as RIS (.ris)
export function exportToRIS(sources: SourceRecord[]): string {
  const lines: string[] = [];

  for (const s of sources) {
    lines.push('TY  - JOUR');
    lines.push(`TI  - ${s.title}`);
    if (s.authors) {
      for (const a of s.authors) {
        lines.push(`AU  - ${a}`);
      }
    }
    if (s.year) lines.push(`PY  - ${s.year}`);
    if (s.venue) lines.push(`JO  - ${s.venue}`);
    if (s.doi) lines.push(`DO  - ${s.doi}`);
    if (s.url) lines.push(`UR  - ${s.url}`);
    lines.push('ER  - \n');
  }

  return lines.join('\n');
}

// Export extraction table to CSV
export function exportTableToCSV(
  columns: Array<{ id: string; name: string }>,
  rows: Array<{ sourceTitle: string; cells: Record<string, { value: string; quote?: string }> }>
): string {
  const escapeCSV = (str: string) => `"${(str || '').replace(/"/g, '""')}"`;

  const headers = ['Source Document', ...columns.map((c) => c.name)];
  const csvLines = [headers.map(escapeCSV).join(',')];

  for (const row of rows) {
    const line = [
      escapeCSV(row.sourceTitle),
      ...columns.map((c) => escapeCSV(row.cells[c.id]?.value || 'N/A')),
    ];
    csvLines.push(line.join(','));
  }

  return csvLines.join('\n');
}

// Export complete Markdown literature review
export function exportLiteratureReviewMarkdown(
  workspaceName: string,
  sources: SourceRecord[],
  synthesisData?: {
    overallSummary?: string;
    themes?: Array<{ name: string; description: string; citations: string[] }>;
    consensus?: Array<{ statement: string; supportingSources: string[] }>;
    conflicts?: Array<{ topic: string; perspectiveA: string; perspectiveB: string }>;
    gaps?: Array<{ gap: string; impact: string; confidence: string }>;
  }
): string {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  let md = `# Literature Review: ${workspaceName}\n\n`;
  md += `*Generated by Lumina-AI on ${date}*\n\n`;
  md += `> **Notice**: All cited findings below are grounded in the active workspace repository. Discovered paper abstracts and uploaded full-text documents are labeled accordingly.\n\n`;

  md += `## Table of Contents\n1. [Executive Summary](#executive-summary)\n2. [Thematic Synthesis](#thematic-synthesis)\n3. [Consensus & Points of Conflict](#consensus--points-of-conflict)\n4. [Identified Research Gaps](#identified-research-gaps)\n5. [Workspace Bibliography](#workspace-bibliography)\n\n---\n\n`;

  md += `## 1. Executive Summary\n${synthesisData?.overallSummary || 'This literature review synthesizes the empirical evidence, theoretical frameworks, and methodologies across all collected workspace documents.'}\n\n`;

  md += `## 2. Thematic Synthesis\n`;
  if (synthesisData?.themes && synthesisData.themes.length > 0) {
    for (const t of synthesisData.themes) {
      md += `### Theme: ${t.name}\n${t.description}\n\n`;
    }
  } else {
    md += `*Analysis of primary themes across the collected literature.*\n\n`;
  }

  md += `## 3. Consensus & Points of Conflict\n`;
  if (synthesisData?.consensus && synthesisData.consensus.length > 0) {
    md += `### Areas of Agreement\n`;
    for (const c of synthesisData.consensus) {
      md += `- **${c.statement}** (Supported by: ${c.supportingSources.join(', ')})\n`;
    }
    md += '\n';
  }

  if (synthesisData?.conflicts && synthesisData.conflicts.length > 0) {
    md += `### Areas of Disagreement & Divergence\n`;
    for (const cf of synthesisData.conflicts) {
      md += `#### ${cf.topic}\n- *Viewpoint A*: ${cf.perspectiveA}\n- *Viewpoint B*: ${cf.perspectiveB}\n\n`;
    }
  }

  md += `## 4. Identified Research Gaps\n`;
  if (synthesisData?.gaps && synthesisData.gaps.length > 0) {
    for (const g of synthesisData.gaps) {
      md += `- **${g.gap}** [Confidence: ${g.confidence}]\n  *Impact*: ${g.impact}\n\n`;
    }
  } else {
    md += `*Future directions and unaddressed empirical questions in the corpus.*\n\n`;
  }

  md += `## 5. Workspace Bibliography\n\n`;
  for (let i = 0; i < sources.length; i++) {
    const s = sources[i];
    const authors = s.authors && s.authors.length > 0 ? s.authors.join(', ') : 'Unknown Authors';
    const year = s.year ? `(${s.year})` : '(n.d.)';
    const doi = s.doi ? ` DOI: [${s.doi}](https://doi.org/${s.doi})` : '';
    const openAccessBadge = s.open_access ? ' [Open Access]' : '';
    md += `${i + 1}. **${authors}** ${year}. *${s.title}*. ${s.venue || 'Repository Source'}.${doi}${openAccessBadge}\n`;
  }

  return md;
}
